#ifndef IMAGE_TRANSFORMER_G24_STATUS_H
#define IMAGE_TRANSFORMER_G24_STATUS_H

enum g24_read_status {
    G24_READ_OK = 0,
    G24_READ_NULL_IMAGE,
    G24_READ_INVALID_HEADER,
    G24_READ_INVALID_BITS,
    G24_READ_OUT_OF_MEMORY,

    G24_READ_STATUSES_NUMBER
};

char* g24_read_status_message(enum g24_read_status status);

#endif //IMAGE_TRANSFORMER_G24_STATUS_H